title: Fun Q
description: "Source files for \"Fun Q: A Functional Introduction to Machine Learning in Q\""
google_analytics:
show_downloads: false
theme: jekyll-theme-hacker

plugins:
  - jekyll-mentions

exclude:
  - xgboost
  - liblinear
  - libsvm
  - ml-latest-small
  - readme
  - SMSSpamCollection
  - dow_jones_index.names
  - test.cmd
  - GNUmakefile
  - "*.dot"
  - "*.txt"
  - "*.ppm"
  - "*.pbm"
  - "*.pgm"
  - "*.data"
  - "*.test"
  - "*.tes"
  - "*.tra"
  - "*.png"
  - "*.png"
  - "*.zip"
  - "*-ubyte"
  - "*.c"
  - "*.h"
  - "*.csv"
  - "*.q"
  - Gemfile*
  - CNAME
  - LICENSE
  - ref.csv
  - errata.adoc